### ISSUE TITLE
Zoom Video Conferences

### ISSUE THREAD

**Issue by tennavan** [robchahin/sso-wall-of-shame#150]
**What is the vendor's name?**
Zoom Video Conferences

**What is the vendor's pricing site?**
https://zoom.us/pricing

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$14.99/user/month

**What is the minimum pricing for SSO support?**
$19.99/user/month

**Does this pricing info come from a quote or other non-public source?**
No

**Are there any caveats we should list in the footnotes?**
The basic Pro Plan is only available for 1 to 9 users and does not include SSO support. The premium Business Plan with SSO support is required for all deployments with 10 or more users.

**Comment by BowlesCR** [comment]
This probably doesn't meet the threshold for an unreasonable price jump.

> 3. attached to a price tier, but with a reasonably small gap between the non-SSO tier and SSO tiers.

**Comment by BowlesCR** [comment]
Also, dupe of #66

**Comment by robchahin** [comment]
Closing as dupe
