### ISSUE TITLE
Sumo Logic Update

### ISSUE THREAD

**Issue by spchin** [robchahin/sso-wall-of-shame#162]
All of Sumo Logic's new offerings include SSO with SAML for no extra charge: https://www.sumologic.com/pricing/

**Comment by Wild1145** [comment]
It's not on their free tier so they're still locking it behind a paywall..?

**Comment by adagioajanes** [comment]
@Wild1145 IMHO, locking SSO from the free tier is acceptable to me. If an application offers single sign on, it should be offered to all of their paid tiers. Per the FAQ, SAML support should be a bare minimum feature for _business_ SaaS. If you are a business, I'd expect that there should be enough funds for at least the basic paid tier.

That's just my personal opinion though.

**Comment by BowlesCR** [comment]
Free doesn't count as "base":

> We disregard free tier pricing, as we can assume these aren’t intended for long term business customer use. We also disregard “single person” pricing, under the assumption that we’re looking on behalf of a team of 5, 10, or more people.

**Comment by robchahin** [comment]
SumoLogic got caught up in a weird merge conflict today so I'm not sure when it might first have been removed, but it's removed now.
