### ISSUE TITLE
Monday.com

### ISSUE THREAD

**Issue by FrankThe** [robchahin/sso-wall-of-shame#178]
**What is the vendor's name?**
Monday.com

**What is the vendor's pricing site?**
https://monday.com/pricing

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$8 per user/month, Minimum 3 users

**What is the minimum pricing for SSO support?**
$37 per user/month with Enterprise, Minimum 5 users

**Does this pricing info come from a quote or other non-public source?**
Quote - Further discounts are available in increments of 1000/users

**Are there any caveats we should list in the footnotes?**
Google SSO is Free, but ONLY Google SSO.

**Comment by robchahin** [comment]
#141
