### ISSUE TITLE
matomo

### ISSUE THREAD

**Issue by tomap** [robchahin/sso-wall-of-shame#181]
**What is the vendor's name?**
matomo

**What is the vendor's pricing site?**
https://matomo.org/pricing/

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
29 per month

**What is the minimum pricing for SSO support?**
on prem: 499$ / cloud: ask for a quote

**Comment by mbainter** [comment]
Given this is now unmaintained, there is now [a fork](stopthessotax/sso-wall-of-shame) that we're hoping to keep maintained via community participation.  If this is still the case with this vendor, would you please submit a fresh issue with current pricing details to that repository?
