### ISSUE TITLE
Add Cloudflare

### ISSUE THREAD

**Issue by gazwilliams** [robchahin/sso-wall-of-shame#219]
**What is the vendor's name?**
Cloudflare

**What is the vendor's pricing site?**
https://www.cloudflare.com/en-gb/plans/

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
Pro is $20/month.

What is the minimum pricing for SSO support?
Enterprise (for SSO) is "call us" from experience its in the region of **$2.5k+ per month**!

**Does this pricing info come from a quote or other non-public source?**
Pro pricing is public, Enterprise from quote over a year ago for my org

**Are there any caveats we should list in the footnotes?**
No RBAC control until enterprise plans either. Makes it impossible to safely share domain management with 3rd party suppliers to my org.

**Comment by robchahin** [comment]
Resolved by #199
