### ISSUE TITLE
Add Calendly

### ISSUE THREAD

**Issue by ozskywalker** [robchahin/sso-wall-of-shame#221]
**What is the vendor's name?**
Calendly

**What is the vendor's pricing site?**
https://calendly.com/pages/pricing

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$8/user/month

**What is the minimum pricing for SSO support?**
"Call us" (Enterprise only tier)

**Does this pricing info come from a quote or other non-public source?**
No, straight from website.

**Are there any caveats we should list in the footnotes?**

**Comment by robchahin** [comment]
There's a PR up for this #234
