### ISSUE TITLE
Atlassian ID 

### ISSUE THREAD

**Issue by delize** [robchahin/sso-wall-of-shame#23]
**What is the vendor's name?**
Atlassian

**What is the vendor's pricing site?**
https://www.atlassian.com/enterprise/cloud/access

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$3

**Does this pricing info come from a quote or other non-public source?**
Included in the above URL

**Are there any caveats we should list in the footnotes?**
None known

**Comment by robchahin** [comment]
Added. Not sure how bad this pricing is since it's flat rate across all Atlassian products, but it's still a solid 45% penalty for a team of 100 using Jira and no other Atlassian products, so probably worth an entry, at least for now.
