### ISSUE TITLE
flip switch to redirect HTTP to HTTPS

### ISSUE THREAD

**Issue by jmhodges** [robchahin/sso-wall-of-shame#267]
Currently, sso.tax gets a scary looking broken lock and doesn't redirect to HTTPS if the link is accidentally written with `http://`. GitHub has a handy "Enforce HTTPS" button that will redirect HTTP requests to sso.tax to its HTTPS equivalent. This gets folks to a secure version and gets rid of the scary looking broken lock in the URL bar.

The instructions are here https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https

Thanks so much for this site! It's handy!

**Comment by robchahin** [comment]
Thought this was already enabled, but it is now. Not sure how long it takes Pages to catch up. Thanks for flagging.

**Comment by jmhodges** [comment]
Thank you!
