### ISSUE TITLE
Add Docker

### ISSUE THREAD

**Issue by eriksw** [robchahin/sso-wall-of-shame#269]
**What is the vendor's name?**
Docker

**What is the vendor's pricing site?**
https://www.docker.com/pricing

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$7/user/month for "Team"

**What is the minimum pricing for SSO support?**
$21/user/month for "Business"

**Does this pricing info come from a quote or other non-public source?**

SSO is exclusive to the "Business" plan per https://www.docker.com/blog/introducing-sso-for-docker-business/:

> SSO is available to organizations with an active Docker Business subscription. This means that customers under the other subscription tiers (e.g., Team) must first upgrade to a Docker Business account.

**Are there any caveats we should list in the footnotes?**

**Comment by eriksw** [comment]
PR already exists: https://github.com/robchahin/sso-wall-of-shame/pull/262

**Comment by lcycon** [comment]
Fixed in #273
