### ISSUE TITLE
Add Cloudsmith.io

### ISSUE THREAD

**Issue by TheAnachronism** [robchahin/sso-wall-of-shame#297]
**What is the vendor's name?**
Cloudsmith

**What is the vendor's pricing site?**
[cloudsmith.com/product/pricing](https://cloudsmith.com/product/pricing/)

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$99/month base, $299/month Advanced
For third, a custom offer is required.

**What is the minimum pricing for SSO support?**
No definitive value.

**Does this pricing info come from a quote or other non-public source?**
The two fixed pricing tiers are available on their site, but the price to use SSO is unknown.

**Are there any caveats we should list in the footnotes?**
The difference from $99 to $299 suggests that the custom one is very pricey. SSO is listed as the last feature on that list, so it also seems like a quite low priority.

**Comment by lskillen** [comment]
Hello! I work at Cloudsmith and just wanted to say two things:

1. SSO is available to all users regardless of the plan, in the form of social authentication and major third-providers (only SAML/Enterprise is tiered here).
2. Security isn't and shouldn't be an enterprise-only feature. Plans are already afoot to make changes here for it to be even more inclusive to all tiers. :)
