### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by schweizerbolzonello** [robchahin/sso-wall-of-shame#31]
**What is the vendor's name?**
Cloudflare
https://blog.cloudflare.com/introducing-single-sign-on-for-the-cloudflare-dashboard/
(It is indicated in the page that SSO is reserved to "Enterprise" customers)

**What is the vendor's pricing site?**
https://www.cloudflare.com/plans/

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
200 USD per month

**What is the minimum pricing for SSO support?**
"Customer Success Manager" must be contacted

**Does this pricing info come from a quote or other non-public source?**
Enterprise plan starts at 5000 USD per month
https://support.cloudflare.com/hc/en-us/articles/200170326-How-much-does-the-Enterprise-Plan-cost-

**Are there any caveats we should list in the footnotes?**
It is indicated in the comments of the following page https://blog.cloudflare.com/introducing-single-sign-on-for-the-cloudflare-dashboard/ that they plan to support it for other customers in the future but it seems a very vague statement.

**Comment by RajUmadas** [comment]
i was surprised by this... :(
