### ISSUE TITLE
Active Project?

### ISSUE THREAD

**Issue by treed593** [robchahin/sso-wall-of-shame#382]
Is this repo still actively maintained? If additional reviewers are needed I would be happy to contribute.

**Comment by sdepablos** [comment]
I don't think it is, I sent a similar message months ago, and the last commit is from 5 months ago

**Comment by treed593** [comment]
Its sad, I know plenty of people would contribute. It can be forked, sure, but would be nice to keep the domain that already has a reputation

**Comment by ironiridis** [comment]
There's definitely real value in this project and its domain with its visibility and notoriety. Hopefully @robchahin is able to renew the domain in October 2023 at least when it expires ( per http://tax.whois-servers.net/ )

**Comment by scottIXP** [comment]
Should we OSINT and see if we can find @robchahin. I work in IDAM and this is one of the small pleasures I have when companies are lolololol with their security pricing!

**Comment by orange-toothbrush** [comment]
Considering the maintainer's radio silence, we should consider forking it. Yes, the domain is valuable, but word of mouth through our networks should help bootstrap the new URL.

**Comment by scottIXP** [comment]
It looks like @robchahin is BACK, which is EXCELLENT! I think we can close this out now, as it is possible to update the main website.

**Comment by robchahin** [comment]
The happiest anyone has ever been to see me, I appreciate the enthusiasm.
