### ISSUE TITLE
Add YoDeck https://www.yodeck.com/pricing/

### ISSUE THREAD

**Issue by jhiggason** [robchahin/sso-wall-of-shame#402]
Yodeck puts SSO behind their enterprise tier of pricing increasing cost over 63% for a security feature.

**Comment by jhiggason** [comment]
What is the vendor's name?
Yodeck.com

What is the vendor's pricing site?
https://www.yodeck.com/pricing/ 

What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.
7.99mo per screen

What is the minimum pricing for SSO support?
12.99mo per screen 62.57% increase. 

Does this pricing info come from a quote or other non-public source?
From website.

Are there any caveats we should list in the footnotes?

**Comment by MMore** [comment]
Hey @jhiggason @alexzuehlke ,

as this repository was not maintained for a long time, I decided to start a new initiative under https://ssotax.org/. The data is already way more up2date than in this repository! Moreover I integrated feedback from the community like a Friends of SSO page. 

Feel free to contribute [there](https://github.com/ssotax/ssotax/). I will merge changes quickly, I promise!
