### ISSUE TITLE
Add Resend

### ISSUE THREAD

**Issue by neilberkman** [robchahin/sso-wall-of-shame#405]
**What is the vendor's name?**
Resend

**What is the vendor's pricing site?**
[https://resend.com/pricing](https://resend.com/pricing)

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$20 per user/month

**What is the minimum pricing for SSO support?**
"Custom"

**Does this pricing info come from a quote or other non-public source?**
no

**Are there any caveats we should list in the footnotes?**
no

**Comment by MMore** [comment]
Hey @neilberkman ,

as this repository was not maintained for a long time, I decided to start a new initiative under https://ssotax.org/. The data is already way more up2date than in this repository! Moreover I integrated feedback from the community like a Friends of SSO page. 

Feel free to contribute [there](https://github.com/ssotax/ssotax/). I will merge changes quickly, I promise!
