### ISSUE TITLE
Quoter

### ISSUE THREAD

**Issue by bitjbullock** [robchahin/sso-wall-of-shame#427]
**What is the vendor's name?**
Quoter

**What is the vendor's pricing site?**
https://www.quoter.com/pricing/

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
199/month

**What is the minimum pricing for SSO support?**
299/month

**Does this pricing info come from a quote or other non-public source?**
all public

**Are there any caveats we should list in the footnotes?**
No

**Comment by MMore** [comment]
Hey @bitjbullock ,

as this repository was not maintained for a long time, I decided to start a new initiative under https://ssotax.org/. The data is already way more up2date than in this repository! Moreover I integrated feedback from the community like a Friends of SSO page. 

Feel free to contribute [there](https://github.com/ssotax/ssotax/). I will merge changes quickly, I promise!
