### ISSUE TITLE
MFA.TAX

### ISSUE THREAD

**Issue by bradwood** [robchahin/sso-wall-of-shame#456]
Are we lumping MFA (2FA) and SSO together in one bucket here? Or are these considered separate taxes?

**Comment by robchahin** [comment]
https://2fa.directory/ preceded sso.tax and looks very different / has different goals, but is the closest thing I know of. If a SaaS vendor implements SSO then they don't need to implement MFA, which is one of a few reasons this site doesn't opine on it.

**Comment by bradwood** [comment]
thanks all -- makes sense! :pray:
