### ISSUE TITLE
StackOverflow

### ISSUE THREAD

**Issue by Chili-Man** [robchahin/sso-wall-of-shame#46]
**What is the vendor's name?**
StackOverflow
**What is the vendor's pricing site?**
https://stackoverflow.com/pricing

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$10/month for first 10 users, extra users $5 per user/month after

**What is the minimum pricing for SSO support?**
Call Us!

**Does this pricing info come from a quote or other non-public source?**
Pricing is direct from the stackover

**Are there any caveats we should list in the footnotes?**
Need to sign up for `Enterprise` for SSO access

**Comment by robchahin** [comment]
https://github.com/robchahin/sso-wall-of-shame/pull/43
