### ISSUE TITLE
PRs are never merged or closed?

### ISSUE THREAD

**Issue by pierreact** [robchahin/sso-wall-of-shame#463]
Question in the title.
What's going on with this project? Do you guys need assistance?

Same question for issues

**Comment by robchahin** [comment]
Merge history is here: https://github.com/robchahin/sso-wall-of-shame/commits/main/

Updates are bursty and best-effort. This has been the case for most of the last 6 years. PRs take priority over issues, and well-formed PRs are merged faster than PRs that require changes.

I appreciate offers of help and have received a few over the years, the site has had a couple of secondary maintainers in its time but we all have hobbies and obligations. I am slow to onboard additional maintainers deliberately.

**Comment by MMore** [comment]
Hey @robchahin ,
maybe you haven't received my emails and other inquiries over the last months. Happy to help and to join forces with ssotax.org. Would love to discuss that so that PRs and other contributions can be integrated more quickly. What do you think?
