### ISSUE TITLE
Raygun

### ISSUE THREAD

**Issue by stevenmiller** [robchahin/sso-wall-of-shame#72]
**What is the vendor's name?**
Raygun

**What is the vendor's pricing site?**
https://raygun.com/pricing

**What is the base pricing? Use the lowest tier that looks sane for a small business customer, not free or personal tiers.**
$79/month

**What is the minimum pricing for SSO support?**
$649/month

**Does this pricing info come from a quote or other non-public source?**
No, all public.

**Are there any caveats we should list in the footnotes?**
Plans below 'Business' include Basic SSO, which includes 'social' SSO providers (they list Facebook as an example). AKA not good for a real business.

**Comment by robchahin** [comment]
This was submitted a PR, so it's now on the site.
